// Code Generated by Sidekick is for learning and experimentation purposes only.
const request = require("supertest");
const app = require("../src/app");

describe("Task Tracker API", () => {
  it("should return health status", async () => {
    const res = await request(app).get("/health");
    expect(res.statusCode).toBe(200);
    expect(res.body.status).toBe("ok");
  });

  it("should return tasks", async () => {
    const res = await request(app).get("/tasks");
    expect(res.statusCode).toBe(200);
    expect(Array.isArray(res.body)).toBe(true);
  });

  it("should create a new task", async () => {
    const res = await request(app)
      .post("/tasks")
      .send({ title: "Write unit tests", status: "Open" });

    expect(res.statusCode).toBe(201);
    expect(res.body.title).toBe("Write unit tests");
  });

  it("should reject task without title", async () => {
    const res = await request(app)
      .post("/tasks")
      .send({ status: "Open" });

    expect(res.statusCode).toBe(400);
  });
});
