// Code Generated by Sidekick is for learning and experimentation purposes only.
const app = require("./app");

const port = process.env.PORT || 3000;

app.listen(port, () => {
  console.log(`Task Tracker API running on port ${port}`);
});
